### ISSUE TITLE
[HELP] Can I customize the key bindings?

### ISSUE THREAD

**Issue by UniqueDing** [dundee/gdu#119]
Thanks for your gdu!, but I use the colemak layout, and hjkl is not suitable for me. I use neio instead of it.

**Comment by daniejstriata** [comment]
keyboard bindings could become a configuration item and toggled from within the TUI.

**Comment by UniqueDing** [comment]
> keyboard bindings could become a configuration item and toggled from within the TUI.

Thanks your reply, but I don't fully understand, can you give me some example.

**Comment by daniejstriata** [comment]
I don't believe it is currently possible. Lets wait for feedback from @dundee

**Comment by dundee** [comment]
Hi @UniqueDing,
it would be possible to implement some sort of configuration for the key bindings but the keys you mentioned (`hjkl`) cannot be changed since they are hardcoded in the implementation of the [table widget](https://github.com/rivo/tview/blob/master/table.go#L1546).

So overall I don't see much benefit for this now.

**Comment by aljustiet** [comment]
Same. I use graphite-angle-kp keyboard layout with h,a,e,i , child of [graphite](https://github.com/rdavison/graphite-layout)
