### ISSUE TITLE
Feature: Add shortcut key 'o' to open file or directory.

### ISSUE THREAD

**Issue by zhangsean** [dundee/gdu#131]
Feature: Add shortcut key `o` to open file or directory.
Sometimes, need open the file or directory to check directory content, make sure is able to delete or not.
Open the selected directory with `Finder` on macOS, with `Explorer` on Windows.
Open the aim file with the default option setting in the system.

**Comment by dundee** [comment]
There are two shortcuts that can be used for this: `v` for showing the content of a file and `b` to spawn shell in the current directory. You can then run whatever you want in the shell.

Is this sufficient for your use case?

**Comment by mez0ru** [comment]
Is there a way to make it work for external applications? using the default associated application with the file type or extension. I think it's a great feature, I have been trying to delete my old files but everytime I don't know what is the content of the file I had to open the file manager and dig it from there. Which takes time since I have a large hdd with thousand of folders and files that I have forgotten existed.

**Comment by zhangsean** [comment]
Some files' content is encoded, for example, videos, audios, or compressed files, which can't discover by showing text content.
A shortcut key `o` to open the file quickly is a much more convenient and useful feature.

**Comment by dundee** [comment]
Not right now. 

I think we could use `EDITOR` ENV variable to start external CLI tool for viewing files and `xdg-open` for starting GUI tools.

**Comment by Impact123** [comment]
> I think we could use `EDITOR` ENV variable to start external CLI tool for viewing files

Have you given more thought about implementing something like this?

**Comment by dundee** [comment]
Not yet, but I hope to get to it next few months.
