### ISSUE TITLE
feat: add ctrl+z for job control support

### ISSUE THREAD

**Issue by yurenchen000** [dundee/gdu#249]
how about add `ctrl+z` for `job control` support?

#192 mentioned this featrue.

maybe I can send a PR

**Comment by yurenchen000** [comment]
here is the RP
https://github.com/dundee/gdu/pull/250

I only tested on ubuntu 22, and it just work.

<br>

seems `tcell` and `tview` not support ctrl+z for job control (so that almost all app based on them also not suppor it)

I can't live without ctrl+z.

here is a wrokaround, I only known It can work on ubuntu.

**Comment by lilydjwg** [comment]
I want this too. Sometimes I just think I don't need the shell and not start tmux before running gdu, only to find later that I do want to check some files. Opening another connection works but takes time, and it's one more window to manage.

`b` works, but it's just not my usual workflow. Exiting current shell is a bit dangerous because I may exit elsewhere accidentally to close the connection and lose my context.

**Comment by yurenchen000** [comment]
@lilydjwg 
exactly, you speak my heart

so I also thought the `b` embed shell should use a different `PS1` prompt

**Comment by dundee** [comment]
https://github.com/dundee/gdu/pull/250 merged, closing.
